services:
  postgres-dev:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: job_finder_dev
    ports:
      - '5431:5432'
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - postgres-network

  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: job_finder_test
    ports:
      - '5433:5432'
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pgdata-dev:
  pgdata-test:

networks:
  postgres-network:
    driver: bridge
